// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttjfnnkgkiomlrlkaeqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0amZubmtna2lvbWxybGthZXF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NzI3NjQsImV4cCI6MjA1ODU0ODc2NH0.0yv-Gs_p9DyE9Uv-dT2vk_kB9-pgQzpRfQnBjuD52FM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);